namespace Sample_CustomNodeImplementation;

/// <summary>
///     Represents sensor data generated by the custom source node.
///     This model simulates IoT sensor readings with timestamp and value.
/// </summary>
public record SensorData
{
    /// <summary>
    ///     Unique identifier for the sensor.
    /// </summary>
    public string SensorId { get; init; } = string.Empty;

    /// <summary>
    ///     Timestamp when the reading was taken.
    /// </summary>
    public DateTime Timestamp { get; init; }

    /// <summary>
    ///     The sensor value (e.g., temperature, pressure, etc.).
    /// </summary>
    public double Value { get; init; }

    /// <summary>
    ///     Unit of measurement for the sensor value.
    /// </summary>
    public string Unit { get; init; } = string.Empty;

    /// <summary>
    ///     Optional metadata about the reading.
    /// </summary>
    public Dictionary<string, object> Metadata { get; init; } = new();
}

/// <summary>
///     Represents processed sensor data after transformation.
///     This model includes calculated metrics and validation status.
/// </summary>
public record ProcessedSensorData
{
    /// <summary>
    ///     Original sensor data.
    /// </summary>
    public SensorData OriginalData { get; init; } = null!;

    /// <summary>
    ///     Processed/calculated value.
    /// </summary>
    public double ProcessedValue { get; init; }

    /// <summary>
    ///     Processing status.
    /// </summary>
    public ProcessingStatus Status { get; init; }

    /// <summary>
    ///     Processing timestamp.
    /// </summary>
    public DateTime ProcessedAt { get; init; }

    /// <summary>
    ///     Additional processing metadata.
    /// </summary>
    public Dictionary<string, object> ProcessingMetadata { get; init; } = new();
}

/// <summary>
///     Represents a batch of processed sensor data for output.
///     This model is used by the batching sink node.
/// </summary>
public record ProcessedDataBatch
{
    /// <summary>
    ///     Batch identifier.
    /// </summary>
    public string BatchId { get; init; } = string.Empty;

    /// <summary>
    ///     Timestamp when the batch was created.
    /// </summary>
    public DateTime CreatedAt { get; init; }

    /// <summary>
    ///     Collection of processed sensor data in this batch.
    /// </summary>
    public IReadOnlyList<ProcessedSensorData> Data { get; init; } = Array.Empty<ProcessedSensorData>();

    /// <summary>
    ///     Batch metadata.
    /// </summary>
    public Dictionary<string, object> BatchMetadata { get; init; } = new();
}

/// <summary>
///     Represents lifecycle events for monitoring node execution.
/// </summary>
public record LifecycleEvent
{
    /// <summary>
    ///     Type of the lifecycle event.
    /// </summary>
    public LifecycleEventType EventType { get; init; }

    /// <summary>
    ///     Name of the node that generated the event.
    /// </summary>
    public string NodeName { get; init; } = string.Empty;

    /// <summary>
    ///     Timestamp when the event occurred.
    /// </summary>
    public DateTime Timestamp { get; init; }

    /// <summary>
    ///     Optional event message.
    /// </summary>
    public string? Message { get; init; }

    /// <summary>
    ///     Additional event metadata.
    /// </summary>
    public Dictionary<string, object> Metadata { get; init; } = new();
}

/// <summary>
///     Processing status enumeration.
/// </summary>
public enum ProcessingStatus
{
    /// <summary>
    ///     Processing succeeded.
    /// </summary>
    Success,

    /// <summary>
    ///     Processing failed with validation error.
    /// </summary>
    ValidationError,

    /// <summary>
    ///     Processing failed with calculation error.
    /// </summary>
    CalculationError,

    /// <summary>
    ///     Processing was skipped.
    /// </summary>
    Skipped,
}

/// <summary>
///     Lifecycle event type enumeration.
/// </summary>
public enum LifecycleEventType
{
    /// <summary>
    ///     Node initialization started.
    /// </summary>
    NodeInitializing,

    /// <summary>
    ///     Node initialization completed.
    /// </summary>
    NodeInitialized,

    /// <summary>
    ///     Node execution started.
    /// </summary>
    NodeExecutionStarted,

    /// <summary>
    ///     Node execution completed.
    /// </summary>
    NodeExecutionCompleted,

    /// <summary>
    ///     Node execution failed.
    /// </summary>
    NodeExecutionFailed,

    /// <summary>
    ///     Node disposal started.
    /// </summary>
    NodeDisposing,

    /// <summary>
    ///     Node disposal completed.
    /// </summary>
    NodeDisposed,
}
