<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
        <PackageReference Include="Testcontainers.Kafka"/>
        <PackageReference Include="Testcontainers.LocalStack"/>
        <PackageReference Include="Testcontainers.MsSql"/>
        <PackageReference Include="Testcontainers.MySql"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
        <PackageReference Include="Testcontainers.RabbitMq"/>
        <PackageReference Include="Testcontainers.ServiceBus"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\tests\NPipeline.Tests.Common\NPipeline.Tests.Common.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Csv\NPipeline.Connectors.Csv.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Json\NPipeline.Connectors.Json.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Excel\NPipeline.Connectors.Excel.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Parquet\NPipeline.Connectors.Parquet.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Http\NPipeline.Connectors.Http.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.SqlServer\NPipeline.Connectors.SqlServer.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Postgres\NPipeline.Connectors.Postgres.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.MySQL\NPipeline.Connectors.MySQL.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.DuckDB\NPipeline.Connectors.DuckDB.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Kafka\NPipeline.Connectors.Kafka.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.RabbitMQ\NPipeline.Connectors.RabbitMQ.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Aws.Sqs\NPipeline.Connectors.Aws.Sqs.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.Connectors.Azure.ServiceBus\NPipeline.Connectors.Azure.ServiceBus.csproj"/>
    </ItemGroup>

</Project>
