//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPipeline.Connectors.Aws.Redshift.Analyzers
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NPipeline.Connectors.Aws.Redshift.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IamRoleArn must be set when WriteStrategy is CopyFromS3.
        /// </summary>
        internal static string REDSHIFT001_Message
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT001_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The CopyFromS3 write strategy requires an IAM role ARN for Redshift to access S3.
        /// </summary>
        internal static string REDSHIFT001_Description
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT001_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing IamRoleArn for CopyFromS3 strategy.
        /// </summary>
        internal static string REDSHIFT001_Title
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT001_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to S3BucketName must be set when WriteStrategy is CopyFromS3.
        /// </summary>
        internal static string REDSHIFT002_Message
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT002_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The CopyFromS3 write strategy requires an S3 bucket name for staging data files.
        /// </summary>
        internal static string REDSHIFT002_Description
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT002_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing S3BucketName for CopyFromS3 strategy.
        /// </summary>
        internal static string REDSHIFT002_Title
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT002_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UpsertKeyColumns must be set when UseUpsert is true.
        /// </summary>
        internal static string REDSHIFT003_Message
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT003_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upsert operations require key columns to match existing rows.
        /// </summary>
        internal static string REDSHIFT003_Description
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT003_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing UpsertKeyColumns for upsert.
        /// </summary>
        internal static string REDSHIFT003_Title
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT003_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Batch size {0} is large. Consider using CopyFromS3 strategy for better performance with large data volumes..
        /// </summary>
        internal static string REDSHIFT004_Message
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT004_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For batch sizes over 10,000 rows, the CopyFromS3 strategy typically provides better performance.
        /// </summary>
        internal static string REDSHIFT004_Description
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT004_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Consider CopyFromS3 for large batch sizes.
        /// </summary>
        internal static string REDSHIFT004_Title
        {
            get
            {
                return ResourceManager.GetString("REDSHIFT004_Title", resourceCulture);
            }
        }
    }
}
