<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591;CA1711</NoWarn>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions"/>
        <PackageReference Include="xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\NPipeline\NPipeline.csproj"/>
        <ProjectReference Include="..\..\src\NPipeline.StorageProviders\NPipeline.StorageProviders.csproj"/>
    </ItemGroup>

</Project>
